name: "工程2: 基本設計"
description: システムアーキテクチャとエンティティモデルの設計
title: "[基本設計] "
labels: ["phase:basic-design", "status:design"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 工程2: 基本設計
        この工程では、システムアーキテクチャとエンティティモデルを設計します。
        担当エージェント: **Software Architect**
        
  - type: input
    id: requirement-issue
    attributes:
      label: Issue番号 (要件定義)
      description: 前工程（要求開発）のIssue番号（複数の場合はカンマ区切りまたはスペース区切り：例 \#123, \#124 または \#123 \#124）
      placeholder: #123 または #123, #124
    validations:
      required: true

  - type: textarea
    id: entity_design
    attributes:
      label: エンティティ設計
      description: 新規/変更するエンティティの設計
      placeholder: |
        ### PetHotelStay
        **継承**: BaseEntity
        
        **フィールド**:
        - checkInDate: LocalDate (@NotNull)
        - checkOutDate: LocalDate (@NotNull)
        - roomNumber: String
        - status: String
        - pet: Pet (@ManyToOne)
      value: |
        ### [エンティティ名]
        **継承**: BaseEntity
        
        **フィールド**:
        - fieldName: Type
        
        **リレーション**:
        - relation: RelatedEntity
    validations:
      required: true

  - type: textarea
    id: database_schema
    attributes:
      label: データベーススキーマ概要
      description: テーブル構造とリレーションシップの概要
      placeholder: |
        - テーブル名: pet_hotel_stays
        - 主キー: id (INTEGER, IDENTITY)
        - 外部キー: pet_id → pets(id)
        - インデックス: pet_id, check_in_date
      value: |
        - テーブル名: table_name
        - 主キー: id
        - 外部キー: foreign_key_id
        - インデックス: index_column
    validations:
      required: true

  - type: textarea
    id: layer_structure
    attributes:
      label: レイヤー構造
      description: 実装する層とコンポーネント
      placeholder: |
        - Entity層: PetHotelStay
        - Repository層: PetHotelStayRepository, SpringDataPetHotelStayRepository
        - Service層: ClinicService (メソッド追加)
        - DTO層: PetHotelStayDto, PetHotelStayFieldsDto
        - Mapper層: PetHotelStayMapper
        - Controller層: PetHotelStayRestController
      value: |
        - Entity層: EntityName
        - Repository層: RepositoryName
        - Service層: ServiceName
        - DTO層: DtoName
        - Mapper層: MapperName
        - Controller層: ControllerName
    validations:
      required: true

  - type: textarea
    id: relationships
    attributes:
      label: エンティティ間のリレーションシップ
      description: 既存エンティティとの関連
      placeholder: |
        - PetHotelStay → Pet: @ManyToOne (多対一)
        - カスケード: CascadeType.MERGE
        - フェッチ: FetchType.LAZY
      value: |
        - EntityA → EntityB: @ManyToOne (relationship type)
    validations:
      required: true

  - type: textarea
    id: architectural_decisions
    attributes:
      label: アーキテクチャ上の決定事項
      description: 重要な設計判断とその理由
      placeholder: |
        1. Visitパターンに従う理由: 既存コードとの一貫性
        2. BaseEntityを継承する理由: ID管理の統一
        3. LocalDateを使用する理由: 日付のみを扱うため
      value: |
        1. 決定事項1とその理由
        2. 決定事項2とその理由
        3. 決定事項3とその理由
    validations:
      required: true

  - type: textarea
    id: consistency_check
    attributes:
      label: 一貫性チェック
      description: 既存アーキテクチャとの整合性確認
      value: |
        - [ ] BaseEntityパターンに従っている
        - [ ] 既存エンティティと一貫性がある
        - [ ] 適切なフェッチ戦略を使用
        - [ ] 適切なカスケード設定
        - [ ] 命名規則に従っている
    validations:
      required: true

  - type: textarea
    id: technical_considerations
    attributes:
      label: 技術的考慮事項
      description: 詳細設計・実装時に考慮すべき事柄
      placeholder: |
        - パフォーマンス: N+1問題やインデックス設計
        - セキュリティ: アクセス管理
        - 拡張性: 新フィールドの追加
      value: |
        - 
        - 
        - 
    validations:
      required: true
      
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 受け入れ基準
      description: この基本設計が完了したと判断する基準
      value: |
        - [ ] エンティティモデルが明確に定義されている
        - [ ] データベーススキーマが設計されている
        - [ ] レイヤー構造が明確である
        - [ ] 既存パターンとの一貫性が確保されている
        - [ ] アーキテクチャ上の決定事項が文書化されている
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 次のステップ
        この基本設計が承認されたら、次の工程「詳細設計」のIssueを作成してください。
        次の工程では、REST API仕様とデータベーススキーマ（DDL）を詳細に設計します。
