name: "工程4: 実装と単体テスト"
description: 詳細設計に基づいたコードの実装と単体テストの作成
title: "[実装と単体テスト] "
labels: ["phase:implementation", "status:in-progress"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 工程4: 実装と単体テスト
        この工程では、詳細設計に基づいてコードを実装し、単体テストを作成します。
        担当エージェント: **Senior Developer**（実装と単体テストの両方を担当）

  - type: input
    id: detailed_design_issue
    attributes:
      label: 詳細設計Issue番号
      description: 前工程（詳細設計）のIssue番号（複数の場合はカンマ区切りまたはスペース区切り：例 \#125, \#126 または \#125 \#126）
      placeholder: #125 または #125, #126
    validations:
      required: true

  - type: checkboxes
    id: implementation_tasks
    attributes:
      label: 実装タスク
      description: 実装する項目
      options:
        - label: データベーススキーマ追加（schema.sql）
        - label: テストデータ追加（data.sql）
        - label: Entityクラス実装
        - label: Repositoryインターフェース実装
        - label: SpringDataRepository実装
        - label: Serviceメソッド追加（ClinicService）
        - label: DTO クラス実装
        - label: Mapper インターフェース実装（MapStruct）
        - label: REST Controller 実装
        - label: OpenAPI仕様更新（openapi.yml）

  - type: textarea
    id: files_to_create
    attributes:
      label: 新規作成ファイル
      description: 新しく作成するファイルのリスト
      placeholder: |
        - src/main/java/org/springframework/samples/petclinic/model/PetHotelStay.java
        - src/main/java/org/springframework/samples/petclinic/repository/PetHotelStayRepository.java
        - src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/SpringDataPetHotelStayRepository.java
        - src/main/java/org/springframework/samples/petclinic/rest/dto/PetHotelStayDto.java
        - src/main/java/org/springframework/samples/petclinic/rest/dto/PetHotelStayFieldsDto.java
        - src/main/java/org/springframework/samples/petclinic/mapper/PetHotelStayMapper.java
        - src/main/java/org/springframework/samples/petclinic/rest/controller/PetHotelStayRestController.java
      value: |
        - 
    validations:
      required: true

  - type: textarea
    id: files_to_modify
    attributes:
      label: 変更するファイル
      description: 既存ファイルで変更が必要なもの
      placeholder: |
        - src/main/java/org/springframework/samples/petclinic/service/ClinicService.java (メソッド追加)
        - src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java (実装追加)
        - src/main/resources/db/h2/schema.sql (テーブル追加)
        - src/main/resources/db/h2/data.sql (データ追加)
        - src/main/resources/openapi.yml (API定義追加)
      value: |
        - 
    validations:
      required: true

  - type: textarea
    id: reference_files
    attributes:
      label: 参考にする既存ファイル
      description: パターンを参考にするファイル
      placeholder: |
        - Visit.java → PetHotelStay.java のパターン
        - VisitRestController.java → PetHotelStayRestController.java のパターン
        - VisitDto.java → PetHotelStayDto.java のパターン
      value: |
        - 
    validations:
      required: true

  - type: checkboxes
    id: coding_standards
    attributes:
      label: コーディング規約チェック
      description: コーディング規約の遵守確認
      options:
        - label: 全てのimportが正しく必要
        - label: コンパイルエラーがない
        - label: 既存パターンに厳密に従っている
        - label: 全てのgetter/setterが実装されている
        - label: 適切なアノテーション（@Entity, @NotNull, @PreAuthorize等）
        - label: コンストラクタインジェクション使用
        - label: finalフィールドで依存関係を宣言
        - label: 命名規則に従っている（PascalCase, camelCase）

  - type: textarea
    id: implementation_notes
    attributes:
      label: 実装メモ
      description: 実装時の特記事項や判断事項
      placeholder: |
        - Visitパターンを完全に踏襲
        - @ManyToOne関係でPetと関連付け
        - LocalDateを使用（日付のみ）
        - MapStructでDTO変換
      value: |
        - 

  - type: checkboxes
    id: build_verification
    attributes:
      label: ビルド確認
      description: ビルドとコンパイルの確認
      options:
        - label: mvn clean compile が成功する
        - label: コンパイルエラーがない
        - label: 警告が最小限である

  - type: markdown
    attributes:
      value: |
        ---
        ## 単体テスト

  - type: checkboxes
    id: test_coverage
    attributes:
      label: テストカバレッジ対象
      description: テストするCRUD操作と状況
      options:
        - label: GET (単一) - 成功ケース (200)
        - label: GET (単一) - 存在しないID (404)
        - label: GET (一覧) - 成功ケース (200)
        - label: GET (一覧) - 空リスト (404)
        - label: POST - 成功ケース (201)
        - label: POST - バリデーションエラー (400)
        - label: PUT - 成功ケース (200)
        - label: PUT - 存在しないID (404)
        - label: DELETE - 成功ケース (204)
        - label: DELETE - 存在しないID (404)

  - type: textarea
    id: test_file
    attributes:
      label: テストファイル
      description: 作成する単体テストファイル
      placeholder: |
        - src/test/java/org/springframework/samples/petclinic/rest/controller/PetHotelStayRestControllerTests.java
      value: |
        - 
    validations:
      required: true

  - type: textarea
    id: reference_test
    attributes:
      label: 参考テストファイル
      description: パターンを参考にする既存テスト
      placeholder: |
        - VisitRestControllerTests.java
      value: |
        - 
    validations:
      required: true

  - type: checkboxes
    id: test_framework
    attributes:
      label: テストフレームワーク/ツール
      description: 使用するテスト技術
      options:
        - label: JUnit 5 (Jupiter)
        - label: Mockito (@MockBean)
        - label: MockMvc
        - label: "@WithMockUser (セキュリティテスト)"
        - label: jsonPath (JSONアサーション)
        - label: ObjectMapper (JSON変換)

  - type: textarea
    id: test_scenarios
    attributes:
      label: テストシナリオ
      description: 実装する主要テストケース
      placeholder: |
        1. testGetAllPetHotelStaysSuccess - 全予約取得成功
        2. testGetAllPetHotelStaysNotFound - 予約が存在しない
        3. testGetPetHotelStaySuccess - 特定予約取得成功
        4. testGetPetHotelStayNotFound - 予約が見つからない
        5. testCreatePetHotelStaySuccess - 予約作成成功
        6. testUpdatePetHotelStaySuccess - 予約更新成功
        7. testUpdatePetHotelStayNotFound - 更新対象が存在しない
        8. testDeletePetHotelStaySuccess - 予約削除成功
        9. testDeletePetHotelStayNotFound - 削除対象が存在しない
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: checkboxes
    id: test_quality
    attributes:
      label: テスト品質チェック
      options:
        - label: 全てのCRUD操作がテストされている
        - label: 成功シナリオ（200, 201, 204）がテストされている
        - label: 失敗シナリオ（404）がテストされている
        - label: バリデーションエラー（400）がテストされている
        - label: "@WithMockUserでセキュリティテスト"
        - label: サービスメソッド呼び出しが検証されている
        - label: JSONレスポンス構造が検証されている
        - label: HTTPヘッダー（Location）が検証されている
        - label: 全テストが独立して実行できる
        - label: テスト名が明確で説明的

  - type: checkboxes
    id: test_execution
    attributes:
      label: テスト実行確認
      options:
        - label: 全てのテストがパスする
        - label: "mvn test が成功する"
        - label: テストカバレッジレポートを生成 (mvn jacoco:report)
        - label: カバレッジレポートを確認 (target/site/jacoco/index.html)
        - label: Line Coverage が85%以上
        - label: Branch Coverage が66%以上

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 受け入れ基準
      value: |
        ## 実装
        - [ ] 全ファイルが作成/更新されている
        - [ ] コードがコンパイルできる
        - [ ] 既存パターンに完全に従っている
        - [ ] 全てのアノテーションが適切
        - [ ] getter/setterが全て実装されている
        - [ ] コンストラクタインジェクションが使用されている
        - [ ] mvn clean compile が成功する
        
        ## 単体テスト
        - [ ] 全てのCRUD操作に対するテストが実装されている
        - [ ] 成功ケースと失敗ケースの両方がテストされている
        - [ ] MockMvcとMockitoが適切に使用されている
        - [ ] @WithMockUserでセキュリティテストが実装されている
        - [ ] 全てのテストがパスする
        - [ ] mvn test が成功する
        - [ ] テストカバレッジレポート (mvn jacoco:report) を生成し、確認した
        - [ ] Line Coverage 85%以上, Branch Coverage 66%以上を達成している
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 次のステップ
        実装と単体テストが完了したら、次の工程「統合テスト」のIssueを作成してください。
        次の工程では、システム全体の統合テストを実施します。
