name: "工程5: 単体テスト"
description: JUnit5とMockitoを使った単体テストの作成
title: "[単体テスト] "
labels: ["phase:unit-test", "status:testing"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 工程5: 単体テスト
        この工程では、実装したコードに対する単体テストを作成します。
        担当エージェント: **QA Engineer**

  - type: input
    id: implementation_issue
    attributes:
      label: 実装Issue番号
      description: 前工程（実装）のIssue番号（複数の場合はカンマ区切りまたはスペース区切り：例 \#126, \#127 または \#126 \#127）
      placeholder: #126 または #126, #127
    validations:
      required: true

  - type: checkboxes
    id: test_coverage
    attributes:
      label: テストカバレッジ対象
      description: テストするCRUD操作と状況
      options:
        - label: GET (単一) - 成功ケース (200)
        - label: GET (単一) - 存在しないID (404)
        - label: GET (一覧) - 成功ケース (200)
        - label: GET (一覧) - 空リスト (404)
        - label: POST - 成功ケース (201)
        - label: POST - バリデーションエラー (400)
        - label: PUT - 成功ケース (200)
        - label: PUT - 存在しないID (404)
        - label: DELETE - 成功ケース (204)
        - label: DELETE - 存在しないID (404)

  - type: textarea
    id: test_file
    attributes:
      label: テストファイル
      description: 作成する単体テストファイル
      placeholder: |
        - src/test/java/org/springframework/samples/petclinic/rest/controller/PetHotelStayRestControllerTests.java
      value: |
        - 
    validations:
      required: true

  - type: textarea
    id: reference_test
    attributes:
      label: 参考テストファイル
      description: パターンを参考にする既存テスト
      placeholder: |
        - VisitRestControllerTests.java
      value: |
        - 
    validations:
      required: true

  - type: checkboxes
    id: test_framework
    attributes:
      label: テストフレームワーク/ツール
      description: 使用するテスト技術
      options:
        - label: JUnit 5 (Jupiter)
        - label: Mockito (@MockBean)
        - label: MockMvc
        - label: "@WithMockUser (セキュリティテスト)"
        - label: jsonPath (JSONアサーション)
        - label: ObjectMapper (JSON変換)

  - type: textarea
    id: test_scenarios
    attributes:
      label: テストシナリオ
      description: 実装する主要テストケース
      placeholder: |
        1. testGetAllPetHotelStaysSuccess - 全予約取得成功
        2. testGetAllPetHotelStaysNotFound - 予約が存在しない
        3. testGetPetHotelStaySuccess - 特定予約取得成功
        4. testGetPetHotelStayNotFound - 予約が見つからない
        5. testCreatePetHotelStaySuccess - 予約作成成功
        6. testUpdatePetHotelStaySuccess - 予約更新成功
        7. testUpdatePetHotelStayNotFound - 更新対象が存在しない
        8. testDeletePetHotelStaySuccess - 予約削除成功
        9. testDeletePetHotelStayNotFound - 削除対象が存在しない
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: mock_setup
    attributes:
      label: モック設定
      description: Mockitoで設定するモック動作
      placeholder: |
        ```java
        given(clinicService.findPetHotelStayById(1)).willReturn(petHotelStay);
        given(clinicService.findAllPetHotelStays()).willReturn(petHotelStayList);
        given(clinicService.findPetHotelStayById(999)).willReturn(null);
        ```
      value: |
        ```java
        given(clinicService.findEntityById(1)).willReturn(entity);
        ```

  - type: textarea
    id: assertions
    attributes:
      label: アサーション
      description: 検証する項目
      placeholder: |
        - HTTPステータスコード (status().isOk(), status().isCreated(), etc.)
        - JSONレスポンスフィールド (jsonPath("$.id").value(1))
        - HTTPヘッダー (header().exists("Location"))
        - サービスメソッド呼び出し (verify(clinicService).saveEntity(entity))
      value: |
        - 

  - type: checkboxes
    id: test_quality
    attributes:
      label: テスト品質チェック
      options:
        - label: 全てのCRUD操作がテストされている
        - label: 成功シナリオ（200, 201, 204）がテストされている
        - label: 失敗シナリオ（404）がテストされている
        - label: バリデーションエラー（400）がテストされている
        - label: "@WithMockUserでセキュリティテスト"
        - label: サービスメソッド呼び出しが検証されている
        - label: JSONレスポンス構造が検証されている
        - label: HTTPヘッダー（Location）が検証されている
        - label: 全テストが独立して実行できる
        - label: テスト名が明確で説明的

  - type: checkboxes
    id: test_execution
    attributes:
      label: テスト実行確認
      options:
        - label: 全てのテストがパスする
        - label: "mvn test が成功する"
        - label: テストカバレッジレポートを生成 (mvn jacoco:report)
        - label: カバレッジレポートを確認 (target/site/jacoco/index.html)
        - label: テストカバレッジが80%以上
        - label: Line Coverage が85%以上
        - label: Branch Coverage が66%以上

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 受け入れ基準
      value: |
        - [ ] 全てのCRUD操作に対するテストが実装されている
        - [ ] 成功ケースと失敗ケースの両方がテストされている
        - [ ] MockMvcとMockitoが適切に使用されている
        - [ ] @WithMockUserでセキュリティテストが実装されている
        - [ ] 全てのテストがパスする
        - [ ] mvn test が成功する
        - [ ] テストカバレッジレポート (mvn jacoco:report) を生成し、確認した
        - [ ] Line Coverage 85%以上, Branch Coverage 66%以上を達成している
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 次のステップ
        単体テストが完了したら、次の工程「統合テスト」のIssueを作成してください。
        次の工程では、システム全体の統合テストを実施します。
